.catalog:
  name: cowpoke
  version: "v2.1.7"
  description: Cowpoke
  questions:
    - variable: rancher_user_key
      label: Rancher Account API Key
      type: string
      required: true
    - variable: rancher_user_secret
      label: Rancher account API secret
      type: password
      required: true
    - variable: rancher_url
      label: Rancher server URL
      type: string
      required: true
    - variable: cert_name
      label: SSL Cert Name
      description: SSL Cert Regestered in Rancher
      type: certificate
      required: true
    - variable: slack_token
      label: Slack Token
      description: Slack access token for deployment notifications
      type: password
    - variable: slack_channels
      label: Slack Channels
      description: Comma delimited list for deployment notification
      type: string

version: "2"
services:
  cowpoke:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      default_cert: "${cert_name}"
      port_rules:
        - priority: 1
          protocol: https
          service: cowpoke-app
          source_port: 9300
          target_port: 9300
    health_check:
      port: 42
      interval: 10000
      unhealthy_threshold: 2
      healthy_threshold: 2
      response_timeout: 2000

  cowpoke-app:
    scale: 1
    start_on_create: true
    health_check:
      port: 9300
      interval: 10000
      unhealthy_threshold: 2
      strategy: none
      request_line: OPTIONS /api HTTP/1.1
      healthy_threshold: 2
      response_timeout: 2000
