version: "2"
services:
  drone-server:
    labels:
      io.rancher.container.pull_image: always
    image: jgreat/drone
    expose:
      - 80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DATABASE_CONFIG: "/var/lib/drone/drone.sqlite"
      DATABASE_DRIVER: "sqlite3"
      REMOTE_DRIVER: "github"
      REMOTE_CONFIG: "https://github.com?client_id=${github_id}&client_secret=${github_secret}"
      SERVER_ADDR: ":80"
      PLUGIN_FILTER: "plugins/* leankit/* jgreat/* arobson/*"
      ESCALATE_FILTER: "plugins/drone-docker plugins/drone-ecr plugins/drone-gcr leankit/drone-docker"
    labels:
      io.rancher.container.pull_image: always

  drone:
    image: rancher/lb-service-haproxy:v0.4.9
    ports:
      - 443:443/tcp
      - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
