.catalog:
  name: drone
  version: 0.4-5
  description: Drone CI
  questions:
    - variable: github_id
      label: GitHub Application API ID
      type: string
      required: true
    - variable: github_secret
      label: GitHub Application API Secret
      type: password
      required: true
    - variable: cert_name
      label: SSL Cert Name
      description: SSL Cert Regestered in Rancher
      type: certificate
      required: true

version: "2"
services:
  drone:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      default_cert: "${cert_name}"
      config: |-
        frontend http-frontend
          bind *:80
          mode http
          redirect scheme https code 302 if !{ ssl_fc }
      port_rules:
        - priority: 1
          protocol: https
          service: drone-server
          source_port: 443
          target_port: 80
    health_check:
      port: 42
      interval: 10000
      unhealthy_threshold: 2
      healthy_threshold: 2
      response_timeout: 2000

  drone-server:
    scale: 1
    health_check:
      port: 80
      interval: 10000
      unhealthy_threshold: 2
      strategy: none
      request_line: ''
      healthy_threshold: 2
      response_timeout: 2000
