.catalog:
  name: RabbitMQ
  version: 3.6.5
  description: RabbitMQ - Single nstance
  questions:
    - variable: username
      label: Username/vHost
      description: vHost will be set as /<username>
      type: string
      required: true
    - variable: password
      label: Password
      type: password
      required: true

version: "2"
  rabbit:
    scale: 1
    start_on_create: true
    health_check:
      port: 5672
      interval: 10000
      unhealthy_threshold: 2
      request_line: ''
      healthy_threshold: 2
      response_timeout: 2000
      strategy: none
